rawData = ```
[
  {
    "CODIGO": "546",
    "DESCRICAO": "BARRA DE ACO CHATA, RETANGULAR (QUALQUER BITOLA)",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "C",
    "PRECO": "8,70"
  },
  {
    "CODIGO": "36218",
    "DESCRICAO": "BARRA DE APOIO RETA, EM ALUMINIO, COMPRIMENTO 60CM, DIAMETRO MINIMO 3 CM",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "155,60"
  },
  {
    "CODIGO": "36220",
    "DESCRICAO": "BARRA DE APOIO RETA, EM ALUMINIO, COMPRIMENTO 70CM, DIAMETRO MINIMO 3 CM",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "178,42"
  },
  {
    "CODIGO": "10535",
    "DESCRICAO": "BETONEIRA CAPACIDADE NOMINAL 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELETRICO TRIFASICO 220/380 V POTENCIA 2 CV, SEM CARREGADOR",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "C",
    "PRECO": "5.450,00"
  },
  {
    "CODIGO": "10537",
    "DESCRICAO": "BETONEIRA CAPACIDADE NOMINAL 400 L, CAPACIDADE DE MISTURA 310 L, MOTOR A DIESEL POTENCIA 5 CV, SEM CARREGADOR",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "7.432,32"
  },
  {
    "CODIGO": "38783",
    "DESCRICAO": "BLOCO CERAMICO / TIJOLO VAZADO PARA ALVENARIA DE VEDACAO, FUROS NA HORIZONTAL DE 11,5 X 19 X 19 CM (L X A X C)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "1,11"
  },
  {
    "CODIGO": "37593",
    "DESCRICAO": "BLOCO CERAMICO / TIJOLO VAZADO PARA ALVENARIA DE VEDACAO, FUROS NA VERTICAL DE 14 X 19 X 39 CM (L X A X C)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "2,73"
  },
  {
    "CODIGO": "37594",
    "DESCRICAO": "BLOCO CERAMICO / TIJOLO VAZADO PARA ALVENARIA DE VEDACAO, FUROS NA VERTICAL DE 19 X 19 X 39 CM (L X A X C)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "3,39"
  },
  {
    "CODIGO": "37592",
    "DESCRICAO": "BLOCO CERAMICO / TIJOLO VAZADO PARA ALVENARIA DE VEDACAO, FUROS NA VERTICAL DE 9 X 19 X 39 CM (L X A X C)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "2,14"
  },
  {
    "CODIGO": "41371",
    "DESCRICAO": "BLOCO CONCRETO CELULAR AUTOCLAVADO 7,5 X 30 X 60 CM (E X A X C)",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "69,22"
  },
  {
    "CODIGO": "34556",
    "DESCRICAO": "BLOCO DE CONCRETO ESTRUTURAL 14 X 19 X 29 CM, FBK 10 MPA (NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "4,73"
  },
  {
    "CODIGO": "37873",
    "DESCRICAO": "BLOCO DE CONCRETO ESTRUTURAL 14 X 19 X 29 CM, FBK 12 MPA (NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "4,81"
  },
  {
    "CODIGO": "34564",
    "DESCRICAO": "BLOCO DE CONCRETO ESTRUTURAL 14 X 19 X 29 CM, FBK 14 MPA (NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "5,04"
  },
  {
    "CODIGO": "34571",
    "DESCRICAO": "BLOCO DE CONCRETO ESTRUTURAL 14 X 19 X 39 CM, FBK 6 MPA (NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "4,39"
  },
  {
    "CODIGO": "34573",
    "DESCRICAO": "BLOCO DE CONCRETO ESTRUTURAL 14 X 19 X 39 CM, FBK 8 MPA (NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "4,62"
  },
  {
    "CODIGO": "37107",
    "DESCRICAO": "BLOCO DE CONCRETO ESTRUTURAL 14 X 19 X 39, FCK 16 MPA (NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "6,11"
  },
  {
    "CODIGO": "34576",
    "DESCRICAO": "BLOCO DE CONCRETO ESTRUTURAL 19 X 19 X 39 CM, FBK 10 MPA (NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "6,74"
  },
  {
    "CODIGO": "709",
    "DESCRICAO": "BLOCO DE POLIETILENO ALTA DENSIDADE, *27* X *30* X *100* CM, ACOMPANHADOS PLACAS TERMINAIS E LONGARINAS, PARA FUNDO DE FILTRO",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "727,92"
  },
  {
    "CODIGO": "34599",
    "DESCRICAO": "BLOCO DE VEDACAO CONCRETO APARENTE 9 X 19 X 39 CM (CLASSE C - NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "3,11"
  },
  {
    "CODIGO": "34592",
    "DESCRICAO": "BLOCO DE VEDACAO CONCRETO 14 X 19 X 29 CM (CLASSE C - NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "3,46"
  },
  {
    "CODIGO": "37103",
    "DESCRICAO": "BLOCO DE VEDACAO DE CONCRETO APARENTE 14 X 19 X 39 CM (CLASSE C - NBR 6136)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "3,96"
  },
  {
    "CODIGO": "34591",
    "DESCRICAO": "BLOCO ESTRUTURAL CERAMICO DE 19 X 19 X 39 CM (L X A X C) E 6,0 MPA",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "3,76"
  },
  {
    "CODIGO": "40517",
    "DESCRICAO": "BLOQUETE/PISO DE CONCRETO - MODELO PISOGRAMA/CONCREGRAMA 2 FUROS, DIMENSOES APROX. DE *35 X 15* CM E ESPESSURA DE 7 CM (+/- 1 CM), COR NATURAL",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "58,25"
  },
  {
    "CODIGO": "40515",
    "DESCRICAO": "BLOQUETE/PISO DE CONCRETO - MODELO PISOGRAMA/CONCREGRAMA/PAVI-GRADE/GRAMEIRO, DIMENSOES APROXIMADAS DE *60 X 45* CM E ESPESSURA DE 8 CM (+/- 1 CM), COR NATURAL",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "131,07"
  },
  {
    "CODIGO": "40524",
    "DESCRICAO": "BLOQUETE/PISO INTERTRAVADO DE CONCRETO - MODELO ONDA/16 FACES/RETANGULAR/TIJOLINHO/PAVER/HOLANDES/PARALELEPIPEDO, *20 X 10* CM, E = 10 CM, RESISTENCIA DE 35 MPA, COR NATURAL",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "81,92"
  },
  {
    "CODIGO": "1330",
    "DESCRICAO": "CHAPA DE ACO GROSSA, ASTM A36, E = 1/4\" (6,35 MM) 49,79 KG/M2",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "8,66"
  },
  {
    "CODIGO": "43667",
    "DESCRICAO": "CHAPA DE ACO GROSSA, ASTM A36, E = 1\" (25,40 MM) 199,18 KG/M2",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "10,50"
  },
  {
    "CODIGO": "10957",
    "DESCRICAO": "CHAPA DE ACO GROSSA, ASTM A36, E = 3/4\" (19,05 MM) 149,39 KG/M2",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "9,99"
  },
  {
    "CODIGO": "1332",
    "DESCRICAO": "CHAPA DE ACO GROSSA, ASTM A36, E = 3/8\" (9,53 MM) 74,69 KG/M2",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "8,88"
  },
  {
    "CODIGO": "34660",
    "DESCRICAO": "CHAPA DE MDF BRANCO LISO 1 FACE, E = 18 MM, DE *2,75 X 1,85* M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "42,40"
  },
  {
    "CODIGO": "34661",
    "DESCRICAO": "CHAPA DE MDF BRANCO LISO 1 FACE, E = 25 MM, DE *2,75 X 1,85* M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "60,90"
  },
  {
    "CODIGO": "34667",
    "DESCRICAO": "CHAPA DE MDF BRANCO LISO 1 FACE, E = 6 MM, DE *2,75 X 1,85* M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "22,05"
  },
  {
    "CODIGO": "34668",
    "DESCRICAO": "CHAPA DE MDF BRANCO LISO 1 FACE, E = 9 MM, DE *2,75 X 1,85* M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "28,82"
  },
  {
    "CODIGO": "1345",
    "DESCRICAO": "CHAPA/PAINEL DE MADEIRA COMPENSADA PLASTIFICADA (MADEIRITE PLASTIFICADO) PARA FORMA DE CONCRETO, DE 2200 X 1100 MM, E = *17* MM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "89,96"
  },
  {
    "CODIGO": "1367",
    "DESCRICAO": "CHUVEIRO COMUM EM PLASTICO CROMADO, COM CANO, 4 TEMPERATURAS (110/220 V)",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "282,94"
  },
  {
    "CODIGO": "1380",
    "DESCRICAO": "CIMENTO BRANCO NAO ESTRUTURAL (CPB - NAO ESTRUTURAL)",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "4,55"
  },
  {
    "CODIGO": "1375",
    "DESCRICAO": "CIMENTO IMPERMEABILIZANTE DE PEGA ULTRARRAPIDA PARA TAMPONAMENTOS",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "17,15"
  },
  {
    "CODIGO": "1379",
    "DESCRICAO": "CIMENTO PORTLAND COMPOSTO CP II-32",
    "UNIDADE DE MEDIDA": "KG",
    "ORIGEM DO PRECO": "C",
    "PRECO": "0,68"
  },
  {
    "CODIGO": "41965",
    "DESCRICAO": "CONCRETO BETUMINOSO USINADO A QUENTE (CBUQ) PARA PAVIMENTACAO ASFALTICA, PADRAO DNIT, PARA BINDER, COM CAP 50/70 - AQUISICAO POSTO USINA",
    "UNIDADE DE MEDIDA": "T",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "466,91"
  },
  {
    "CODIGO": "1524",
    "DESCRICAO": "CONCRETO USINADO BOMBEAVEL, CLASSE DE RESISTENCIA C20, BRITA 0 E 1, SLUMP = 100 +/- 20 MM, COM BOMBEAMENTO (DISPONIBILIZACAO DE BOMBA), SEM O LANCAMENTO (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "609,97"
  },
  {
    "CODIGO": "34492",
    "DESCRICAO": "CONCRETO USINADO BOMBEAVEL, CLASSE DE RESISTENCIA C20, COM BRITA 0 E 1, SLUMP = 100 +/- 20 MM, EXCLUI SERVICO DE BOMBEAMENTO (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "C",
    "PRECO": "565,00"
  },
  {
    "CODIGO": "38405",
    "DESCRICAO": "CONCRETO USINADO BOMBEAVEL, CLASSE DE RESISTENCIA C25, COM BRITA 0 E 1, SLUMP = 130 +/- 20 MM, EXCLUI SERVICO DE BOMBEAMENTO (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "603,28"
  },
  {
    "CODIGO": "38408",
    "DESCRICAO": "CONCRETO USINADO BOMBEAVEL, CLASSE DE RESISTENCIA C25, COM BRITA 0 E 1, SLUMP = 190 +/- 20 MM, EXCLUI SERVICO DE BOMBEAMENTO (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "667,77"
  },
  {
    "CODIGO": "1525",
    "DESCRICAO": "CONCRETO USINADO BOMBEAVEL, CLASSE DE RESISTENCIA C30, BRITA 0 E 1, SLUMP = 100 +/- 20 MM, COM BOMBEAMENTO (DISPONIBILIZACAO DE BOMBA), SEM O LANCAMENTO (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "648,70"
  },
  {
    "CODIGO": "34494",
    "DESCRICAO": "CONCRETO USINADO BOMBEAVEL, CLASSE DE RESISTENCIA C30, COM BRITA 0 E 1, SLUMP = 100 +/- 20 MM, EXCLUI SERVICO DE BOMBEAMENTO (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "600,29"
  },
  {
    "CODIGO": "34485",
    "DESCRICAO": "CONCRETO USINADO BOMBEAVEL, CLASSE DE RESISTENCIA C60, COM BRITA 0 E 1, SLUMP = 100 +/- 20 MM, COM BOMBEAMENTO (DISPONIBILIZACAO DE BOMBA), SEM O LANCAMENTO (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "820,68"
  },
  {
    "CODIGO": "14041",
    "DESCRICAO": "CONCRETO USINADO CONVENCIONAL (NAO BOMBEAVEL) CLASSE DE RESISTENCIA C10, COM BRITA 1 E 2, SLUMP = 80 MM +/- 10 MM (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "533,48"
  },
  {
    "CODIGO": "1523",
    "DESCRICAO": "CONCRETO USINADO CONVENCIONAL (NAO BOMBEAVEL) CLASSE DE RESISTENCIA C15, COM BRITA 1 E 2, SLUMP = 80 MM +/- 10 MM (NBR 8953)",
    "UNIDADE DE MEDIDA": "M3",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "542,19"
  },
  {
    "CODIGO": "10911",
    "DESCRICAO": "JUNCAO INVERTIDA, PVC SOLDAVEL, 75 X 75 MM, SERIE NORMAL PARA ESGOTO PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "16,11"
  },
  {
    "CODIGO": "38383",
    "DESCRICAO": "LIXA D'AGUA EM FOLHA, GRAO 100",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "2,06"
  },
  {
    "CODIGO": "3768",
    "DESCRICAO": "LIXA EM FOLHA PARA FERRO, NUMERO 150",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "2,38"
  },
  {
    "CODIGO": "3767",
    "DESCRICAO": "LIXA EM FOLHA PARA PAREDE OU MADEIRA, NUMERO 120, COR VERMELHA",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "0,79"
  },
  {
    "CODIGO": "12410",
    "DESCRICAO": "LUVA DE REDUCAO DE FERRO GALVANIZADO, COM ROSCA BSP MACHO/FEMEA, DE 3/4\" X 1/2",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "15,05"
  },
  {
    "CODIGO": "3936",
    "DESCRICAO": "LUVA DE REDUCAO DE FERRO GALVANIZADO, COM ROSCA BSP, DE 1 1/2\" X 1 1/4",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "27,20"
  },
  {
    "CODIGO": "3922",
    "DESCRICAO": "LUVA DE REDUCAO DE FERRO GALVANIZADO, COM ROSCA BSP, DE 1 1/2\" X 1/2",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "25,02"
  },
  {
    "CODIGO": "3924",
    "DESCRICAO": "LUVA DE REDUCAO DE FERRO GALVANIZADO, COM ROSCA BSP, DE 1 1/2\" X 1",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "27,20"
  },
  {
    "CODIGO": "3923",
    "DESCRICAO": "LUVA DE REDUCAO DE FERRO GALVANIZADO, COM ROSCA BSP, DE 1 1/2\" X 3/4",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "27,20"
  },
  {
    "CODIGO": "3937",
    "DESCRICAO": "LUVA DE REDUCAO DE FERRO GALVANIZADO, COM ROSCA BSP, DE 1 1/4\" X 1/2",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "22,44"
  },
  {
    "CODIGO": "36324",
    "DESCRICAO": "LUVA SIMPLES PPR, F/F, SOLDAVEL, DN 25 MM, PARA AGUA QUENTE PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "2,00"
  },
  {
    "CODIGO": "38441",
    "DESCRICAO": "LUVA SIMPLES PPR, F/F, SOLDAVEL, DN 32 MM, PARA AGUA QUENTE PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "3,59"
  },
  {
    "CODIGO": "38442",
    "DESCRICAO": "LUVA SIMPLES PPR, F/F, SOLDAVEL, DN 40 MM, PARA AGUA QUENTE PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "10,20"
  },
  {
    "CODIGO": "38443",
    "DESCRICAO": "LUVA SIMPLES PPR, F/F, SOLDAVEL, DN 50 MM, PARA AGUA QUENTE PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "12,38"
  },
  {
    "CODIGO": "38444",
    "DESCRICAO": "LUVA SIMPLES PPR, F/F, SOLDAVEL, DN 63 MM, PARA AGUA QUENTE PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "20,79"
  },
  {
    "CODIGO": "38445",
    "DESCRICAO": "LUVA SIMPLES PPR, F/F, SOLDAVEL, DN 75 MM, PARA AGUA QUENTE PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "38,54"
  },
  {
    "CODIGO": "38446",
    "DESCRICAO": "LUVA SIMPLES PPR, F/F, SOLDAVEL, DN 90 MM, PARA AGUA QUENTE PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "63,08"
  },
  {
    "CODIGO": "37456",
    "DESCRICAO": "MANGUEIRA CRISTAL PARA NIVEL, LISA, PVC TRANSPARENTE, 5/16\" X1 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "2,22"
  },
  {
    "CODIGO": "37461",
    "DESCRICAO": "MANGUEIRA CRISTAL TRANCADA, PVC COM REFORCO, COM PRESSAO DE TRABALHO (PT) 250 LBS/POL2, DE 3/4\" X *2,8* MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "15,61"
  },
  {
    "CODIGO": "37460",
    "DESCRICAO": "MANGUEIRA CRISTAL TRANCADA, PVC COM REFORCO, PRESSAO DE TRABALHO (PT) 250 LBS/POL2, DE 1\" X *3,4* MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "21,32"
  },
  {
    "CODIGO": "37458",
    "DESCRICAO": "MANGUEIRA CRISTAL, LISA, PVC TRANSPARENTE, 1/2\" X 2 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "C",
    "PRECO": "6,25"
  },
  {
    "CODIGO": "37454",
    "DESCRICAO": "MANGUEIRA CRISTAL, LISA, PVC TRANSPARENTE, 1/4\" X1 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "1,64"
  },
  {
    "CODIGO": "37455",
    "DESCRICAO": "MANGUEIRA CRISTAL, LISA, PVC TRANSPARENTE, 1/4\" X1,5 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "2,76"
  },
  {
    "CODIGO": "37459",
    "DESCRICAO": "MANGUEIRA CRISTAL, LISA, PVC TRANSPARENTE, 3/4\" X 2 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "8,77"
  },
  {
    "CODIGO": "21029",
    "DESCRICAO": "MANGUEIRA DE INCENDIO, TIPO 1, DE 1 1/2\", COMPRIMENTO = 15 M, TECIDO EM FIO DE POLIESTER E TUBO INTERNO EM BORRACHA SINTETICA, COM UNIOES ENGATE RAPIDO",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "C",
    "PRECO": "300,00"
  },
  {
    "CODIGO": "7088",
    "DESCRICAO": "TE, PVC PBA, BBB, 90 GRAUS, DN 75 / DE 85 MM, PARA REDE DE AGUA",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "44,25"
  },
  {
    "CODIGO": "20179",
    "DESCRICAO": "TE, PVC, SERIE R, 100 X 100 MM, PARA ESGOTO PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "38,41"
  },
  {
    "CODIGO": "20178",
    "DESCRICAO": "TE, PVC, SERIE R, 100 X 75 MM, PARA ESGOTO PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "46,04"
  },
  {
    "CODIGO": "20180",
    "DESCRICAO": "TE, PVC, SERIE R, 150 X 100 MM, PARA ESGOTO PREDIAL",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "75,99"
  },
  {
    "CODIGO": "7155",
    "DESCRICAO": "TELA DE ACO SOLDADA NERVURADA, CA-60, Q-138, (2,20 KG/M2), DIAMETRO DO FIO = 4,2 MM, LARGURA = 2,45 M, ESPACAMENTO DA MALHA = 10 X 10 CM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "14,97"
  },
  {
    "CODIGO": "42406",
    "DESCRICAO": "TELA DE ACO SOLDADA NERVURADA, CA-60, Q-159, (2,52 KG/M2), DIAMETRO DO FIO = 4,5 MM, LARGURA = 2,45 M, ESPACAMENTO DA MALHA = 10 X 10 CM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "17,16"
  },
  {
    "CODIGO": "7156",
    "DESCRICAO": "TELA DE ACO SOLDADA NERVURADA, CA-60, Q-196, (3,11 KG/M2), DIAMETRO DO FIO = 5,0 MM, LARGURA = 2,45 M, ESPACAMENTO DA MALHA = 10 X 10 CM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "C",
    "PRECO": "21,48"
  },
  {
    "CODIGO": "43127",
    "DESCRICAO": "TELA DE ACO SOLDADA NERVURADA, CA-60, Q-283 (4,48 KG/M2), DIAMETRO DO FIO = 6,0 MM, LARGURA = 2,45 X 6,00 M DE COMPRIMENTO, ESPACAMENTO DA MALHA = 10 X 10 CM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "30,74"
  },
  {
    "CODIGO": "10917",
    "DESCRICAO": "TELA DE ACO SOLDADA NERVURADA, CA-60, Q-61, (0,97 KG/M2), DIAMETRO DO FIO = 3,4 MM, LARGURA = 2,45 M, ESPACAMENTO DA MALHA = 15 X 15 CM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "6,49"
  },
  {
    "CODIGO": "21141",
    "DESCRICAO": "TELA DE ACO SOLDADA NERVURADA, CA-60, Q-92, (1,48 KG/M2), DIAMETRO DO FIO = 4,2 MM, LARGURA = 2,45 X 60 M DE COMPRIMENTO, ESPACAMENTO DA MALHA = 15 X 15 CM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "10,04"
  },
  {
    "CODIGO": "39509",
    "DESCRICAO": "TELA DE ACO SOLDADA NERVURADA, CA-60, T-196, (2,11 KG/M2), DIAMETRO DO FIO = 5,0 MM, LARGURA = 2,45 M, ESPACAMENTO DA MALHA = 30 X 10 CM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "9,66"
  },
  {
    "CODIGO": "44529",
    "DESCRICAO": "TELA DE ANIAGEM ( JUTA)",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "18,87"
  },
  {
    "CODIGO": "7167",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA QUADRANGULAR / LOSANGULAR, FIO 2,11 MM (14 BWG), MALHA 5 X 5 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "26,53"
  },
  {
    "CODIGO": "10928",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA QUADRANGULAR / LOSANGULAR, FIO 2,11 MM (14 BWG), MALHA 8 X 8 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "15,24"
  },
  {
    "CODIGO": "10933",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA QUADRANGULAR / LOSANGULAR, FIO 2,77 MM (12 BWG), MALHA 10 X 10 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "22,99"
  },
  {
    "CODIGO": "7158",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA QUADRANGULAR / LOSANGULAR, FIO 2,77 MM (12 BWG), MALHA 5 X 5 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "C",
    "PRECO": "39,00"
  },
  {
    "CODIGO": "10927",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA QUADRANGULAR / LOSANGULAR, FIO 2,77 MM (12 BWG), MALHA 8 X 8 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "24,94"
  },
  {
    "CODIGO": "7162",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA QUADRANGULAR / LOSANGULAR, FIO 3,4 MM (10 BWG), MALHA 5 X 5 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "61,03"
  },
  {
    "CODIGO": "10932",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA QUADRANGULAR / LOSANGULAR, FIO 4,19 MM (8 BWG), MALHA 5 X 5 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "106,15"
  },
  {
    "CODIGO": "10937",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA REVESTIDA EM PVC, QUADRANGULAR / LOSANGULAR, FIO 2,11 MM (14 BWG), BITOLA FINAL = *2,8* MM, MALHA *8 X 8* CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "27,28"
  },
  {
    "CODIGO": "10935",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA REVESTIDA EM PVC, QUADRANGULAR / LOSANGULAR, FIO 2,77 MM (12 BWG), BITOLA FINAL = *3,8* MM, MALHA 7,5 X 7,5 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "47,32"
  },
  {
    "CODIGO": "10931",
    "DESCRICAO": "TELA DE ARAME GALVANIZADA, HEXAGONAL, FIO 0,56 MM (24 BWG), MALHA 1/2\", H = 1 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "13,31"
  },
  {
    "CODIGO": "7164",
    "DESCRICAO": "TELA DE ARAME ONDULADA, FIO *2,77* MM (12 BWG), MALHA 5 X 5 CM, H = 2 M",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "44,05"
  },
  {
    "CODIGO": "36887",
    "DESCRICAO": "TELA DE FIBRA DE VIDRO, ACABAMENTO ANTI-ALCALINO, MALHA 10 X 10 MM",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "9,10"
  },
  {
    "CODIGO": "34630",
    "DESCRICAO": "TELA EM MALHA HEXAGONAL DE DUPLA TORCAO 8 X 10 CM (ZN/AL REVESTIDO COM POLIMERO), FIO 2,7 MM, COM GEOMANTA OU BIOMANTA, DIMENSOES 4,0 X 2,0 X 0,6 M, COM INCLINACAO DE 70 GRAUS, PARA SOLO REFORCADO",
    "UNIDADE DE MEDIDA": "UN",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "1.087,29"
  },
  {
    "CODIGO": "7161",
    "DESCRICAO": "TELA EM METAL PARA ESTUQUE (DEPLOYE)",
    "UNIDADE DE MEDIDA": "M2",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "5,48"
  },
  {
    "CODIGO": "7754",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-2, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 900 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "944,75"
  },
  {
    "CODIGO": "7735",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-3, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 1000 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "1.223,35"
  },
  {
    "CODIGO": "7755",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-3, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 400 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "242,61"
  },
  {
    "CODIGO": "7776",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-3, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 500 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "505,78"
  },
  {
    "CODIGO": "7743",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-3, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 600 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "535,60"
  },
  {
    "CODIGO": "7733",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-3, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 700 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "699,05"
  },
  {
    "CODIGO": "7775",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-3, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 800 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "765,87"
  },
  {
    "CODIGO": "7734",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO PARA ESGOTO SANITARIO, CLASSE EA-3, COM ENCAIXE PONTA E BOLSA, COM JUNTA ELASTICA, DIAMETRO NOMINAL DE 900 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "1.084,56"
  },
  {
    "CODIGO": "7714",
    "DESCRICAO": "TUBO DE CONCRETO ARMADO, PRE MOLDADO PARA AGUAS PLUVIAIS, CLASSE PA-1, COM ENCAIXE PONTA E BOLSA, DIAMETRO NOMINAL DE 500 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "151,11"
  },
  {
    "CODIGO": "37449",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE MACHO E FEMEA, DIAMETRO NOMINAL DE 200 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "36,86"
  },
  {
    "CODIGO": "37450",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE MACHO E FEMEA, DIAMETRO NOMINAL DE 300 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "51,61"
  },
  {
    "CODIGO": "37451",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE MACHO E FEMEA, DIAMETRO NOMINAL DE 400 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "72,05"
  },
  {
    "CODIGO": "37452",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE MACHO E FEMEA, DIAMETRO NOMINAL DE 500 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "104,72"
  },
  {
    "CODIGO": "37453",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE MACHO E FEMEA, DIAMETRO NOMINAL DE 600 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "120,60"
  },
  {
    "CODIGO": "7778",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE PONTA E BOLSA, DIAMETRO NOMINAL DE 200 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "45,24"
  },
  {
    "CODIGO": "7796",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE PONTA E BOLSA, DIAMETRO NOMINAL DE 300 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "62,00"
  },
  {
    "CODIGO": "7781",
    "DESCRICAO": "TUBO DE CONCRETO SIMPLES PARA AGUAS PLUVIAIS, CLASSE PS1, COM ENCAIXE PONTA E BOLSA, DIAMETRO NOMINAL DE 400 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "73,26"
  },
  {
    "CODIGO": "44547",
    "DESCRICAO": "TUBO DE POLIETILENO DE ALTA DENSIDADE, PEAD, PE-80, DE= 200 MM X 18,2 MM PAREDE, (SDR 11 - PN 12,5) PARA REDE DE AGUA OU ESGOTO (NBR 15561)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "411,80"
  },
  {
    "CODIGO": "38054",
    "DESCRICAO": "TUBO DRENO, CORRUGADO, ESPIRALADO, FLEXIVEL, PERFURADO, EM POLIETILENO DE ALTA DENSIDADE (PEAD), DN *200* MM, (8\") PARA DRENAGEM - EM BARRA (NORMA DNIT 093/2006 - EM)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "44,95"
  },
  {
    "CODIGO": "38052",
    "DESCRICAO": "TUBO DRENO, CORRUGADO, ESPIRALADO, FLEXIVEL, PERFURADO, EM POLIETILENO DE ALTA DENSIDADE (PEAD), DN 100 MM, (4\") PARA DRENAGEM - EM ROLO (NORMA DNIT 093/2006 - E.M)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "12,66"
  },
  {
    "CODIGO": "38051",
    "DESCRICAO": "TUBO DRENO, CORRUGADO, ESPIRALADO, FLEXIVEL, PERFURADO, EM POLIETILENO DE ALTA DENSIDADE (PEAD), DN 65 MM, (2 1/2\") PARA DRENAGEM - EM ROLO (NORMA DNIT 093/2006 - EM)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "7,89"
  },
  {
    "CODIGO": "38787",
    "DESCRICAO": "TUBO MONOCAMADA PEX, DN 16 MM, PARA AGUA QUENTE E FRIA",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "4,82"
  },
  {
    "CODIGO": "38974",
    "DESCRICAO": "TUBO PPR, CLASSE PN 12, DN 63 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "36,01"
  },
  {
    "CODIGO": "38975",
    "DESCRICAO": "TUBO PPR, CLASSE PN 12, DN 75 MM",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "46,17"
  },
  {
    "CODIGO": "38984",
    "DESCRICAO": "TUBO PPR, CLASSE PN 25, DN 75 MM, PARA AGUA QUENTE E FRIA PREDIAL",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "100,30"
  },
  {
    "CODIGO": "38985",
    "DESCRICAO": "TUBO PPR, CLASSE PN 25, DN 90 MM, PARA AGUA QUENTE E FRIA PREDIAL",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "172,44"
  },
  {
    "CODIGO": "38032",
    "DESCRICAO": "TUBO PVC CORRUGADO, PAREDE DUPLA, JE, DN 150 MM/ DE 160 MM, REDE COLETORA ESGOTO",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "51,68"
  },
  {
    "CODIGO": "38033",
    "DESCRICAO": "TUBO PVC CORRUGADO, PAREDE DUPLA, JE, DN 200 MM/ DE 200 MM, REDE COLETORA ESGOTO",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "87,86"
  },
  {
    "CODIGO": "9828",
    "DESCRICAO": "TUBO PVC DEFOFO, JEI, 1 MPA, DN 150 MM, PARA REDE DE AGUA (NBR 7665)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "102,24"
  },
  {
    "CODIGO": "9829",
    "DESCRICAO": "TUBO PVC DEFOFO, JEI, 1 MPA, DN 200 MM, PARA REDE DE AGUA (NBR 7665)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "173,28"
  },
  {
    "CODIGO": "9826",
    "DESCRICAO": "TUBO PVC DEFOFO, JEI, 1 MPA, DN 250 MM, PARA REDE DE AGUA (NBR 7665)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "263,79"
  },
  {
    "CODIGO": "9827",
    "DESCRICAO": "TUBO PVC DEFOFO, JEI, 1 MPA, DN 300 MM, PARA REDE DE AGUA (NBR 7665)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "AS",
    "PRECO": "374,58"
  },
  {
    "CODIGO": "9859",
    "DESCRICAO": "TUBO PVC ROSCAVEL, 3/4\", AGUA FRIA PREDIAL",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "9,99"
  },
  {
    "CODIGO": "9836",
    "DESCRICAO": "TUBO PVC SERIE NORMAL, DN 100 MM, PARA ESGOTO PREDIAL (NBR 5688)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "C",
    "PRECO": "13,08"
  },
  {
    "CODIGO": "20065",
    "DESCRICAO": "TUBO PVC SERIE NORMAL, DN 150 MM, PARA ESGOTO PREDIAL (NBR 5688)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "34,19"
  },
  {
    "CODIGO": "9835",
    "DESCRICAO": "TUBO PVC SERIE NORMAL, DN 40 MM, PARA ESGOTO PREDIAL (NBR 5688)",
    "UNIDADE DE MEDIDA": "M",
    "ORIGEM DO PRECO": "CR",
    "PRECO": "5,71"
  }
]
```;

// Insert select options from data
document.addEventListener("DOMContentLoaded", function () {
  console.log("Criando insumos");
  const selectElement = document.getElementById("supplyName");

  let data = rawData.json();
  data.forEach((supply) => {
    const option = document.createElement("option");
    option.value = supply["DESCRICAO"];
    option.textContent = supply["DESCRICAO"];
    selectElement.appendChild(option);
  });
});

// Search price from selected option
document.addEventListener("DOMContentLoaded", function () {
  const form = document.querySelector("form");
  form.onsubmit = function (event) {
    event.preventDefault();
    const supplyName = document.getElementById("supplyName").value;

    let data = rawData.json();
    data.forEach((supply) => {
      const supply = data.find((s) => s["DESCRICAO"] === supplyName);
      if (supply) {
        alert(
          `Preço do Insumo: R$ ${supply["PRECO"]} / ${supply["UNIDADE DE MEDIDA"]}`
        );
      } else {
        alert("Insumo não encontrado.");
      }
    });
  };
});
